### ISSUE TITLE
Projects using this fail to compile under Pop_OS

### ISSUE THREAD

**Issue by ZoeyR** [dotnet/Nerdbank.GitVersioning#490] opened 2020-07-23 02:05 UTC
When compiling on Pop_OS (The ubuntu derivative used on system76 laptops) the following exception occurs:

System.PlatformNotSupportedException: pop.20.04-x64

**Comment by AArnott** [comment] 2020-07-23 13:21
Duplicate of #482. In particular notice this comment: https://github.com/dotnet/Nerdbank.GitVersioning/issues/482#issuecomment-633728078

**Closed by AArnott** 2020-07-23 13:21 UTC
