### ISSUE TITLE
unable to get version from commit when try to build project in travis ci

### ISSUE THREAD

**Issue by chucklu** [dotnet/Nerdbank.GitVersioning#518] opened 2020-10-12 11:13 UTC
The build log is here https://travis-ci.com/github/ChuckFork/SuperSocket/builds/189458596

> /home/travis/.nuget/packages/nerdbank.gitversioning/3.1.91/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018: The "Nerdbank.GitVersioning.Tasks.GetBuildVersion" task failed unexpectedly. [/home/travis/build/ChuckFork/SuperSocket/src/SuperSocket.ProtoBase/SuperSocket.ProtoBase.csproj]
> /home/travis/.nuget/packages/nerdbank.gitversioning/3.1.91/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018: System.InvalidOperationException: Unable to get version from commit: 66d5b142fd34af7603b1bbde9eefa3645086d84f [/home/travis/build/ChuckFork/SuperSocket/src/SuperSocket.ProtoBase/SuperSocket.ProtoBase.csproj]
> /home/travis/.nuget/packages/nerdbank.gitversioning/3.1.91/build/Nerdbank.GitVersioning.targets(71,5): error MSB4018:  ---> System.NullReferenceException: Object reference not set to an instance of an object.

**Comment by AArnott** [comment] 2020-10-17 20:30
Duplicate of #174

**Closed by AArnott** 2020-10-17 20:30 UTC

**Comment by chucklu** [comment] 2020-11-06 07:35
[Documentation to disable shallow clone on Travis CI](https://docs.travis-ci.com/user/customizing-the-build/#Git-Clone-Depth)
```yml
git:
  depth: false
```
