### ISSUE TITLE
Support for signing tags with `dotnet nbgv tag`

### ISSUE THREAD

**Issue by alexrp** [dotnet/Nerdbank.GitVersioning#785] opened 2022-07-14 15:07 UTC
It would be nice if `dotnet nbgv tag` could get an option to sign commits. Currently, I have to do something like:

```
dotnet nbgv tag
# Update tag as signed and with message set to its name (signed tags require a message).
git tag v0.1.2 v0.1.2 -f -m v0.1.2 -s
```

Being able to instead do `dotnet nbgv tag -s` would be much nicer. Bonus points for an `-m` option, though I'm perfectly happy with just using the tag name as the message.

**Comment by AArnott** [comment] 2022-07-14 23:55
Ya, we'll close as a duplicate of #594

**Closed by AArnott** 2022-07-14 23:55 UTC
