### ISSUE TITLE
Add a way to log the contents of Version.cs and Version.New.cs when different

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/Nerdbank.GitVersioning#642] opened 2021-08-13 23:30 UTC
We're tuning incremental builds and noticing that NBGV is touching Version.cs when we don't think it should be. For further investigation it would be helpful if it logged the actual contents of both files.

Since the files are just a dozen or so lines I think it's reasonable to either always log them in that place:
![image](https://user-images.githubusercontent.com/679326/129426914-4a5ffc29-b818-4fa0-bfb1-2833d10ec839.png)

or have a property we can set to have them logged. I think reading the file text and assigning to a property would be sufficient as we can then view the value of the property in the binlog.

Or any other way.

**Comment by KirillOsenkov** [comment] 2021-08-13 23:31
We think https://github.com/dotnet/Nerdbank.GitVersioning/issues/175 may be related, as it's a desktop WPF scenario with wpftmp markup compilation.

**Comment by AArnott** [comment] 2021-08-14 04:25
If it's a consistent problem, can you just save the file before a build and then diff it with the file after the build?

**Comment by KirillOsenkov** [comment] 2021-08-14 21:43
I suppose I could. Will try it next time.

**Comment by KirillOsenkov** [comment] 2023-09-30 03:23
Still seeing this (it breaks incremental builds).

The file contents are identical, but the Copy operation still overwrites the destination file even if the contents are identical.

To repro:
```
git clone https://github.com/KirillOsenkov/MSBuildStructuredLog
cd MSBuildStructuredLog
msbuild /r /m /bl:1.binlog MSBuildStructuredLog.sln
msbuild /r /m /bl:2.binlog MSBuildStructuredLog.sln
```

The second build isn't expected to do any work, but it still rebuilds the StructuredLogViewer.csproj because the generated StructuredLogViewer.Version.cs is touched by the copy task.

![image](https://github.com/dotnet/Nerdbank.GitVersioning/assets/679326/f6a76ca2-2b02-45ef-9675-903ee3ad8267)

**Comment by KirillOsenkov** [comment] 2023-09-30 03:26
In fact, I'm not sure NBGV tasks should even run during wpftmp builds (??)

**Comment by AArnott** [comment] 2023-09-30 15:55
NBGV _does_ need to run during wpftmp builds, or else code-behind files that reference `ThisAssembly` fail to compile. 
I'll take a look into the copy issue.

**Comment by AArnott** [comment] 2023-09-30 16:10
Duplicate of #175 (at least, in the sense that the root problem is the same).

**Closed by AArnott** 2023-09-30 16:10 UTC
